# This is a basic workflow that is manually triggered

name: Dev Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  trigger_qa:
    runs-on: ubuntu-latest
    needs: build
     steps:
      - name: Dispatch QA Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_REPO_TOKEN }}
          repository: trieuquan27/testrepodispatch
          event-type: qa_workflow
