# This is a basic workflow that is manually triggered

name: Dev Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dispatch QA Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_REPO_TOKEN }}
          repository: trieuquan27/testrepodispatch
          event-type: qa_workflow
