# This is a basic workflow that is automatically triggered when push on master branch

name: Dev Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  trigger-test:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch QA Workflow
        id: dispatch_qa_workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_REPO_TOKEN }}
          repository: trieuquan27/testrepodispatch
          event-type: qa_workflow

      - name: Get Workflow ID
        id: get_workflow_id
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/repos/trieuquan27/testrepodispatch/actions/workflows)
          workflow_id=$(echo "$response" | jq -r '.workflows[] | select(.name == "Playwright Tests") | .id')
          echo "::set-output name=workflow_id::$workflow_id"
        shell: bash

     - name: Wait for QA Workflow
        if: ${{ steps.dispatch_qa_workflow.outputs.status == 'queued' || steps.dispatch_qa_workflow.outputs.status == 'in_progress' }}
        run: |
          echo "Waiting for QA Workflow to complete..."
          while true; do
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/trieuquan27/testrepodispatch/actions/runs?workflow_id=${{ steps.get_workflow_id.outputs.workflow_id }}&event=repository_dispatch&branch=master")
            conclusion=$(echo "$response" | jq -r '.workflow_runs[0].conclusion')
            if [ "$conclusion" != "null" ]; then
              if [ "$conclusion" == "success" ]; then
                echo "QA Workflow completed successfully."
                break
              else
                echo "QA Workflow failed with conclusion: $conclusion"
                exit 1
              fi
            else
              echo "QA Workflow is still in progress..."
              sleep 10
            fi
          done