# This is a basic workflow that is automatically triggered when push on master branch

name: Dev Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  trigger-test:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch QA Workflow
        id: dispatch_qa_workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_REPO_TOKEN }}
          repository: trieuquan27/testrepodispatch
          event-type: qa_workflow

      - name: Get Workflow ID
        id: get_workflow_id
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/repos/trieuquan27/testrepodispatch/actions/workflows)
          workflow_id=$(echo "$response" | jq -r '.workflows[] | select(.name == "Playwright Tests") | .id')
          echo "::set-output name=workflow_id::$workflow_id"
        shell: bash

      - name: Wait for QA Workflow
        if: ${{ steps.dispatch_qa_workflow.outputs.status == 'queued' || steps.dispatch_qa_workflow.outputs.status == 'in_progress' }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: runs } = await github.actions.listWorkflowRuns({
              owner: 'trieuquan27',
              repo: 'testrepodispatch',
              workflow_id: '${{ steps.get_workflow_id.outputs.workflow_id }}',
              event: 'repository_dispatch',
              branch: 'master'
            });
            const latestRun = runs.workflow_runs.find(run => run.status === 'completed');
            if (latestRun.conclusion === 'success') {
              console.log('QA Workflow completed successfully.');
            } else {
              console.log(`QA Workflow failed with conclusion: ${latestRun.conclusion}`);
              process.exit(1);
            }
