# This is a basic workflow that is automatically triggered when push on master branch

name: Dev Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  trigger-test:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch QA Workflow
        id: dispatch_qa_workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_REPO_TOKEN }}
          repository: trieuquan27/test.github.io
          event-type: qa_workflow
          workflow_file_name: selftest.yaml
          client_payload: '{"test": "true"}'
          wait_interval: 11
          trigger_workflow: true
          wait_workflow: true
          propagate_failure: true
