# This is a basic workflow that is automatically triggered when push on master branch

name: Dev Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  trigger-test:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch QA Workflow
        id: dispatch_qa_workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_REPO_TOKEN }}
          repository: trieuquan27/test.github.io
          event-type: qa_workflow

  call-workflow-in-another-repo:
    uses: trieuquan27/test/.github/workflows/playwright.yml
